### ISSUE TITLE
Error: ENOENT, no such file or directory 'node_modules/syntux/node_modules/highlight.js/lib/languages'

### ISSUE THREAD

**Issue by ccorcos** [DylanPiercey/Syntux#3]
(env)~/c/styleguide ❯❯❯ npm install syntux --save                                                                                                                                               
## npm WARN package.json styleguide@0.0.1 No repository field.

> syntux@0.3.5 postinstall /Users/chetcorcos/code/styleguide/node_modules/syntux
> npm install gulp && gulp build

gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.1 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── minimist@1.2.0
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── semver@4.3.6
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, dateformat@1.0.11, multipipe@0.1.2)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, findup-sync@0.3.0, resolve@1.1.6)
└── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
fs.js:765
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/chetcorcos/code/styleguide/node_modules/syntux/node_modules/highlight.js/lib/languages'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at Object.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/syntux/gulpfile.js:9:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/chetcorcos/code/styleguide/node_modules/syntux/node_modules/gulp/bin/gulp.js:116:3)
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/chetcorcos/code/styleguide/env/bin/node" "/Users/chetcorcos/code/styleguide/env/bin/npm" "install" "syntux" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! syntux@0.3.5 postinstall: `npm install gulp && gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the syntux@0.3.5 postinstall script 'npm install gulp && gulp build'.
npm ERR! This is most likely a problem with the syntux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install gulp && gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls syntux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chetcorcos/code/styleguide/npm-debug.log

**Comment by DylanPiercey** [comment]
What version of npm are you using?

**Comment by ccorcos** [comment]
```
(env)~/c/styleguide ❯❯❯ npm --version                                                                                                                                                           
2.5.1
```

**Comment by DylanPiercey** [comment]
I'll check this out later today. Thanks

**Comment by DylanPiercey** [comment]
This should be fixed as of de5194aeb7c19b946df6e2fca9ba44a3832aa716.

Let me know if there are any other issues.

**Comment by ccorcos** [comment]
did you publish this to npm?

**Comment by ccorcos** [comment]
Still an issue

```
~/c/styleguide ❯❯❯ npm install --save syntux                                                                                                                                                                                                                                    master ✱
npm WARN package.json styleguide@0.0.1 No repository field.
npm WARN package.json styleguide@0.0.1 No README data
npm WARN package.json styleguide@0.0.1 No license field.
-
> syntux@0.4.0 postinstall /Users/chetcorcos/code/styleguide/node_modules/syntux
> node ./lib/build.js

fs.js:813
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/chetcorcos/code/styleguide/node_modules/syntux/node_modules/highlight.js/lib/languages'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.<anonymous> (/Users/chetcorcos/code/styleguide/node_modules/syntux/lib/build.js:9:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install" "--save" "syntux"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! syntux@0.4.0 postinstall: `node ./lib/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the syntux@0.4.0 postinstall script 'node ./lib/build.js'.
npm ERR! This is most likely a problem with the syntux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls syntux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chetcorcos/code/styleguide/npm-debug.log
```

**Comment by DylanPiercey** [comment]
I've tried this on a few machines and it has worked on all of them. Perhaps try manually deleting syntux from your node modules and reinstall?

**Comment by ccorcos** [comment]
I think this is wrong

https://github.com/DylanPiercey/Syntux/blob/master/lib/build.js#L6

it ought to be __dirname + '../../highlight.js'

highlight.js is in my node_modules directory, not in the syntux directory

**Comment by ccorcos** [comment]
oh weird. I got it to work. Highlight.js was already installed by another package, so it existed in the toplevel node modules and wasnt copied into syntux. I deleted highlight.js and it worked. Somethign is wrong herre though. Try installing highlight.js separately and then installing syntux
