### ISSUE TITLE
Only displays first charater

### ISSUE THREAD

**Issue by ccorcos** [DylanPiercey/Syntux#4]
`<JS>{ 'var x = 10;' }</JS>` only displays a single "v"

https://github.com/DylanPiercey/Syntux/blob/master/lib/language.js#L8

**Comment by ccorcos** [comment]
`"react": "^0.13.3",`

**Comment by DylanPiercey** [comment]
Let me know if this has been resolved with 0.4.1

**Comment by ccorcos** [comment]
> Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.

right here:

```
            React.Children.only(this.props.children),
```

**Comment by DylanPiercey** [comment]
You should only be passing one child to the component. Can you show me how you are using this?

**Comment by ccorcos** [comment]
`<JS>{this.props.usage}</JS>`

I upgraded to react 0.14.0.

**Comment by DylanPiercey** [comment]
I have not tested with 0.14 so it's unlikely to work. once I get some time I may fix this. You are welcome to make a PR.

**Comment by ccorcos** [comment]
sounds good.
